{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cart-api.fullname" . }}-postgres
  labels:
    {{- include "cart-api.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: postgres
    {{- include "cart-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.servicePort }}
      targetPort: {{ .Values.postgres.servicePort }}
  type: ClusterIP
{{- end }}

