apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cart-api.fullname" . }}-secret
  labels:
    {{- include "cart-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASS: {{ .Values.secret.postgresPassword | quote }}

