apiVersion: v1
kind: Service
metadata:
  name: {{ include "cart-api.fullname" . }}
  labels:
    {{- include "cart-api.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: app
    {{- include "cart-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}

