apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-api-config
  namespace: test
data:
  HTTP_PORT: "3000"
  POSTGRES_HOST: "cart-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "carts"

