apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart-postgres-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeName: cart-postgres-pv

